<a href="https://colab.research.google.com/github/BoktiarChy/BoktiarChy/blob/main/Average%20world%20Population%20from%201961%20to%202016.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data = pd.read_csv('https://tinyurl.com/ChrisCoDV/world_population.csv', index_col=0)


data

Country Code  \
Country Name                    
Aruba                     ABW   
Andorra                   AND   
Afghanistan               AFG   
Angola                    AGO   
Albania                   ALB   
...                       ...   
Yemen, Rep.               YEM   
South Africa              ZAF   
Congo, Dem. Rep.          COD   
Zambia                    ZMB   
Zimbabwe                  ZWE   

                                                     Indicator Name  \
Country Name                                                          
Aruba             Population density (people per sq. km of land ...   
Andorra           Population density (people per sq. km of land ...   
Afghanistan       Population density (people per sq. km of land ...   
Angola            Population density (people per sq. km of land ...   
Albania           Population density (people per sq. km of land ...   
...                                                             ...   
Yemen, Rep.       Population density (people per sq. km of land ...   
South Africa      Population density (people per sq. km of land ...   
Congo, Dem. Rep.  Population density (people per sq. km of land ...   
Zambia            Population density (people per sq. km of land ...   
Zimbabwe          Population density (people per sq. km of land ...   

                 Indicator Code  1960        1961        1962        1963  \
Country Name                                                                
Aruba               EN.POP.DNST   NaN  307.972222  312.366667  314.983333   
Andorra             EN.POP.DNST   NaN   30.587234   32.714894   34.914894   
Afghanistan         EN.POP.DNST   NaN   14.038148   14.312061   14.599692   
Angola              EN.POP.DNST   NaN    4.305195    4.384299    4.464433   
Albania             EN.POP.DNST   NaN   60.576642   62.456898   64.329234   
...                         ...   ...         ...         ...         ...   
Yemen, Rep.         EN.POP.DNST   NaN    9.946897   10.112857   10.283730   
South Africa        EN.POP.DNST   NaN   14.796892   15.216878   15.609838   
Congo, Dem. Rep.    EN.POP.DNST   NaN    6.897825    7.075824    7.261381   
Zambia              EN.POP.DNST   NaN    4.227724    4.359305    4.496824   
Zimbabwe            EN.POP.DNST   NaN   10.021037   10.356112   10.703901   

                        1964        1965        1966  ...        2007  \
Country Name                                          ...               
Aruba             316.827778  318.666667  320.622222  ...  562.322222   
Andorra            37.170213   39.470213   41.800000  ...  180.591489   
Afghanistan        14.901579   15.218206   15.545203  ...   39.637202   
Angola              4.544558    4.624228    4.703271  ...   15.387749   
Albania            66.209307   68.058066   69.874927  ...  108.394781   
...                      ...         ...         ...  ...         ...   
Yemen, Rep.        10.460234   10.642972   10.834968  ...   41.102913   
South Africa       15.984431   16.348334   16.708236  ...   40.060326   
Congo, Dem. Rep.    7.456342    7.661877    7.878900  ...   26.393275   
Zambia              4.639914    4.788452    4.942343  ...   17.135926   
Zimbabwe           11.062585   11.431128   11.809022  ...   34.374559   

                        2008        2009        2010        2011        2012  \
Country Name                                                                   
Aruba             563.011111  563.422222  564.427778  566.311111  568.850000   
Andorra           182.161702  181.859574  179.614894  175.161702  168.757447   
Afghanistan        40.634655   41.674005   42.830327   44.127634   45.533197   
Angola             15.915819   16.459536   17.020898   17.600302   18.196544   
Albania           107.566204  106.843759  106.314635  106.013869  105.848431   
...                      ...         ...         ...         ...         ...   
Yemen, Rep.        42.280241   43.476383   44.684304   45.902116   47.1

In [10]:
data= data.transpose()
print(data.head())


Country Name                                                Aruba  \
Country Code                                                  ABW   
Indicator Name  Population density (people per sq. km of land ...   
Indicator Code                                        EN.POP.DNST   
1960                                                          NaN   
1961                                                   307.972222   

Country Name                                              Andorra  \
Country Code                                                  AND   
Indicator Name  Population density (people per sq. km of land ...   
Indicator Code                                        EN.POP.DNST   
1960                                                          NaN   
1961                                                    30.587234   

Country Name                                          Afghanistan  \
Country Code                                                  AFG   
Indicator Name  Population densi

We dont need some of the rows. So, we are dropping the rows. 

In [11]:
#Drop rows

selected= ['Country Code', 'Indicator Name', 'Indicator Code']

data= data.drop(selected, axis=0)
print(data)





Country Name       Aruba     Andorra Afghanistan     Angola     Albania  \
1960                 NaN         NaN         NaN        NaN         NaN   
1961          307.972222   30.587234   14.038148   4.305195   60.576642   
1962          312.366667   32.714894   14.312061   4.384299   62.456898   
1963          314.983333   34.914894   14.599692   4.464433   64.329234   
1964          316.827778   37.170213   14.901579   4.544558   66.209307   
1965          318.666667   39.470213   15.218206   4.624228   68.058066   
1966          320.622222        41.8   15.545203   4.703271   69.874927   
1967          322.494444   44.159574   15.881812   4.782892   71.737153   
1968          324.361111   46.570213   16.235931   4.865721   73.805547   
1969          326.244444   49.065957   16.618433   4.955244    75.97427   
1970          328.138889   51.657447   17.034429   5.054118    77.93719   
1971          330.211111   54.382979   17.481269   5.163748    79.84865   
1972          332.494444 

In [12]:
#Sorting 

data=data.reindex(data.mean().sort_values(ascending=False).index, axis=1)

In [13]:
print(data.mean())


Country Name
Macao SAR, China        15403.478649
Monaco                  14643.918182
Hong Kong SAR, China     5370.407475
Singapore                4731.118204
Gibraltar                2688.887273
                            ...     
Namibia                     1.702577
Mongolia                    1.272402
Greenland                   0.141078
Not classified                   NaN
South Sudan                      NaN
Length: 264, dtype: float64


**China , Monaco and Hongkong are the largest three country in therms of average population density with 15403, 14643 and 5370 people respectively.**

In [14]:
select2= data.columns[data.mean()> 5000]

data= data[select2]

print(data)


data.plot.line()
plt.show()

Country Name Macao SAR, China   Monaco Hong Kong SAR, China
1960                      NaN      NaN                  NaN
1961                  8756.75  11406.0          3105.980392
1962                  9051.25  11521.0          3240.392157
1963                  9435.15  11584.5          3353.823529
1964                  9876.15  11618.5          3435.882353
1965                  10345.5  11641.5          3527.352941
1966                 10843.65  11652.0           3558.72549
1967                  11362.9  11648.5          3649.803922
1968                 11856.45  11648.0          3728.137255
1969                  12265.5  11674.0          3788.137255
1970                 12549.85  11742.0          3881.372549
1971                 12694.05  11861.0          3965.980392
1972                  12714.1  12026.0          4042.745098
1973                 12642.25  12220.0          4158.431373
1974                  12527.5  12417.5          4249.215686
1975                 12410.65  12600.5  